version: 2
jobs: 
  lint: 
    docker: 
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: echo "npm linting" 
      - run: npm install
      - run: npm run lint
  build: 
    docker: 
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: echo "npm installing" 
      - run: npm install
      - run: CI=true npm run build
workflows:
  version: 2
  lint_and_build: 
    jobs:
      - lint 
      - build